apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - image: asdfghjklxd/peerprep-user-service:latest
        imagePullPolicy: Always
        name: user-service
        ports:
        - containerPort: 8001
        resources:
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: USER_SERVICE_PORT
              name: peerprep-secrets
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: ACCESS_TOKEN_SECRET
              name: peerprep-secrets
        - name: MONGO_PROD_URI
          valueFrom:
            secretKeyRef:
              key: USER_SERVICE_MONGO_PROD_URI
              name: peerprep-secrets

---

kind: Service
apiVersion: v1
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: user-service
      protocol: TCP
      port: 8001
      targetPort: 8001

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
